// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.network.bbcb.net.proto;

public final class UsersProto {
  private UsersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WXLoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:users_proto.WXLoginReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *微信凭证
     * </pre>
     *
     * <code>optional string code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *微信凭证
     * </pre>
     *
     * <code>optional string code = 1;</code>
     */
    java.lang.String getCode();
    /**
     * <pre>
     *微信凭证
     * </pre>
     *
     * <code>optional string code = 1;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();
  }
  /**
   * Protobuf type {@code users_proto.WXLoginReq}
   */
  public  static final class WXLoginReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:users_proto.WXLoginReq)
      WXLoginReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WXLoginReq.newBuilder() to construct.
    private WXLoginReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WXLoginReq() {
      code_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WXLoginReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WXLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              code_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.network.bbcb.net.proto.UsersProto.WXLoginReq.class, com.network.bbcb.net.proto.UsersProto.WXLoginReq.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object code_;
    /**
     * <pre>
     *微信凭证
     * </pre>
     *
     * <code>optional string code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *微信凭证
     * </pre>
     *
     * <code>optional string code = 1;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *微信凭证
     * </pre>
     *
     * <code>optional string code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.network.bbcb.net.proto.UsersProto.WXLoginReq)) {
        return super.equals(obj);
      }
      com.network.bbcb.net.proto.UsersProto.WXLoginReq other = (com.network.bbcb.net.proto.UsersProto.WXLoginReq) obj;

      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (!getCode()
            .equals(other.getCode())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.network.bbcb.net.proto.UsersProto.WXLoginReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code users_proto.WXLoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:users_proto.WXLoginReq)
        com.network.bbcb.net.proto.UsersProto.WXLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.network.bbcb.net.proto.UsersProto.WXLoginReq.class, com.network.bbcb.net.proto.UsersProto.WXLoginReq.Builder.class);
      }

      // Construct using com.network.bbcb.net.proto.UsersProto.WXLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginReq_descriptor;
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.WXLoginReq getDefaultInstanceForType() {
        return com.network.bbcb.net.proto.UsersProto.WXLoginReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.WXLoginReq build() {
        com.network.bbcb.net.proto.UsersProto.WXLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.WXLoginReq buildPartial() {
        com.network.bbcb.net.proto.UsersProto.WXLoginReq result = new com.network.bbcb.net.proto.UsersProto.WXLoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.network.bbcb.net.proto.UsersProto.WXLoginReq) {
          return mergeFrom((com.network.bbcb.net.proto.UsersProto.WXLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.network.bbcb.net.proto.UsersProto.WXLoginReq other) {
        if (other == com.network.bbcb.net.proto.UsersProto.WXLoginReq.getDefaultInstance()) return this;
        if (other.hasCode()) {
          bitField0_ |= 0x00000001;
          code_ = other.code_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.network.bbcb.net.proto.UsersProto.WXLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.network.bbcb.net.proto.UsersProto.WXLoginReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object code_ = "";
      /**
       * <pre>
       *微信凭证
       * </pre>
       *
       * <code>optional string code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *微信凭证
       * </pre>
       *
       * <code>optional string code = 1;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *微信凭证
       * </pre>
       *
       * <code>optional string code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *微信凭证
       * </pre>
       *
       * <code>optional string code = 1;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *微信凭证
       * </pre>
       *
       * <code>optional string code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *微信凭证
       * </pre>
       *
       * <code>optional string code = 1;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:users_proto.WXLoginReq)
    }

    // @@protoc_insertion_point(class_scope:users_proto.WXLoginReq)
    private static final com.network.bbcb.net.proto.UsersProto.WXLoginReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.network.bbcb.net.proto.UsersProto.WXLoginReq();
    }

    public static com.network.bbcb.net.proto.UsersProto.WXLoginReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WXLoginReq>
        PARSER = new com.google.protobuf.AbstractParser<WXLoginReq>() {
      @java.lang.Override
      public WXLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WXLoginReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WXLoginReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WXLoginReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.network.bbcb.net.proto.UsersProto.WXLoginReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:users_proto.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *访问我方服务器的凭证
     * </pre>
     *
     * <code>optional string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <pre>
     *访问我方服务器的凭证
     * </pre>
     *
     * <code>optional string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *访问我方服务器的凭证
     * </pre>
     *
     * <code>optional string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *和token一起，用于验证登录合法性
     * </pre>
     *
     * <code>optional string uuid = 2;</code>
     */
    boolean hasUuid();
    /**
     * <pre>
     *和token一起，用于验证登录合法性
     * </pre>
     *
     * <code>optional string uuid = 2;</code>
     */
    java.lang.String getUuid();
    /**
     * <pre>
     *和token一起，用于验证登录合法性
     * </pre>
     *
     * <code>optional string uuid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     *会员号
     * </pre>
     *
     * <code>optional string memberid = 3;</code>
     */
    boolean hasMemberid();
    /**
     * <pre>
     *会员号
     * </pre>
     *
     * <code>optional string memberid = 3;</code>
     */
    java.lang.String getMemberid();
    /**
     * <pre>
     *会员号
     * </pre>
     *
     * <code>optional string memberid = 3;</code>
     */
    com.google.protobuf.ByteString
        getMemberidBytes();

    /**
     * <pre>
     *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    boolean hasPhonenumber();
    /**
     * <pre>
     *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    java.lang.String getPhonenumber();
    /**
     * <pre>
     *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhonenumberBytes();
  }
  /**
   * Protobuf type {@code users_proto.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:users_proto.UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      token_ = "";
      uuid_ = "";
      memberid_ = "";
      phonenumber_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              token_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              uuid_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              memberid_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              phonenumber_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.network.bbcb.net.proto.UsersProto.UserInfo.class, com.network.bbcb.net.proto.UsersProto.UserInfo.Builder.class);
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *访问我方服务器的凭证
     * </pre>
     *
     * <code>optional string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *访问我方服务器的凭证
     * </pre>
     *
     * <code>optional string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *访问我方服务器的凭证
     * </pre>
     *
     * <code>optional string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uuid_;
    /**
     * <pre>
     *和token一起，用于验证登录合法性
     * </pre>
     *
     * <code>optional string uuid = 2;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *和token一起，用于验证登录合法性
     * </pre>
     *
     * <code>optional string uuid = 2;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *和token一起，用于验证登录合法性
     * </pre>
     *
     * <code>optional string uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object memberid_;
    /**
     * <pre>
     *会员号
     * </pre>
     *
     * <code>optional string memberid = 3;</code>
     */
    public boolean hasMemberid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *会员号
     * </pre>
     *
     * <code>optional string memberid = 3;</code>
     */
    public java.lang.String getMemberid() {
      java.lang.Object ref = memberid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memberid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *会员号
     * </pre>
     *
     * <code>optional string memberid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMemberidBytes() {
      java.lang.Object ref = memberid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 4;
    private volatile java.lang.Object phonenumber_;
    /**
     * <pre>
     *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    public boolean hasPhonenumber() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    public java.lang.String getPhonenumber() {
      java.lang.Object ref = phonenumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phonenumber_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhonenumberBytes() {
      java.lang.Object ref = phonenumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phonenumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uuid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, memberid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phonenumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, memberid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phonenumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.network.bbcb.net.proto.UsersProto.UserInfo)) {
        return super.equals(obj);
      }
      com.network.bbcb.net.proto.UsersProto.UserInfo other = (com.network.bbcb.net.proto.UsersProto.UserInfo) obj;

      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (hasUuid() != other.hasUuid()) return false;
      if (hasUuid()) {
        if (!getUuid()
            .equals(other.getUuid())) return false;
      }
      if (hasMemberid() != other.hasMemberid()) return false;
      if (hasMemberid()) {
        if (!getMemberid()
            .equals(other.getMemberid())) return false;
      }
      if (hasPhonenumber() != other.hasPhonenumber()) return false;
      if (hasPhonenumber()) {
        if (!getPhonenumber()
            .equals(other.getPhonenumber())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasMemberid()) {
        hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
        hash = (53 * hash) + getMemberid().hashCode();
      }
      if (hasPhonenumber()) {
        hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPhonenumber().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.network.bbcb.net.proto.UsersProto.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code users_proto.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:users_proto.UserInfo)
        com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_UserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.network.bbcb.net.proto.UsersProto.UserInfo.class, com.network.bbcb.net.proto.UsersProto.UserInfo.Builder.class);
      }

      // Construct using com.network.bbcb.net.proto.UsersProto.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        memberid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        phonenumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_UserInfo_descriptor;
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.UserInfo getDefaultInstanceForType() {
        return com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.UserInfo build() {
        com.network.bbcb.net.proto.UsersProto.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.UserInfo buildPartial() {
        com.network.bbcb.net.proto.UsersProto.UserInfo result = new com.network.bbcb.net.proto.UsersProto.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.memberid_ = memberid_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.phonenumber_ = phonenumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.network.bbcb.net.proto.UsersProto.UserInfo) {
          return mergeFrom((com.network.bbcb.net.proto.UsersProto.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.network.bbcb.net.proto.UsersProto.UserInfo other) {
        if (other == com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000002;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasMemberid()) {
          bitField0_ |= 0x00000004;
          memberid_ = other.memberid_;
          onChanged();
        }
        if (other.hasPhonenumber()) {
          bitField0_ |= 0x00000008;
          phonenumber_ = other.phonenumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.network.bbcb.net.proto.UsersProto.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.network.bbcb.net.proto.UsersProto.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *访问我方服务器的凭证
       * </pre>
       *
       * <code>optional string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *访问我方服务器的凭证
       * </pre>
       *
       * <code>optional string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *访问我方服务器的凭证
       * </pre>
       *
       * <code>optional string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *访问我方服务器的凭证
       * </pre>
       *
       * <code>optional string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *访问我方服务器的凭证
       * </pre>
       *
       * <code>optional string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *访问我方服务器的凭证
       * </pre>
       *
       * <code>optional string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <pre>
       *和token一起，用于验证登录合法性
       * </pre>
       *
       * <code>optional string uuid = 2;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *和token一起，用于验证登录合法性
       * </pre>
       *
       * <code>optional string uuid = 2;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *和token一起，用于验证登录合法性
       * </pre>
       *
       * <code>optional string uuid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *和token一起，用于验证登录合法性
       * </pre>
       *
       * <code>optional string uuid = 2;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *和token一起，用于验证登录合法性
       * </pre>
       *
       * <code>optional string uuid = 2;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *和token一起，用于验证登录合法性
       * </pre>
       *
       * <code>optional string uuid = 2;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object memberid_ = "";
      /**
       * <pre>
       *会员号
       * </pre>
       *
       * <code>optional string memberid = 3;</code>
       */
      public boolean hasMemberid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *会员号
       * </pre>
       *
       * <code>optional string memberid = 3;</code>
       */
      public java.lang.String getMemberid() {
        java.lang.Object ref = memberid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            memberid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *会员号
       * </pre>
       *
       * <code>optional string memberid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMemberidBytes() {
        java.lang.Object ref = memberid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memberid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会员号
       * </pre>
       *
       * <code>optional string memberid = 3;</code>
       */
      public Builder setMemberid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memberid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会员号
       * </pre>
       *
       * <code>optional string memberid = 3;</code>
       */
      public Builder clearMemberid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        memberid_ = getDefaultInstance().getMemberid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会员号
       * </pre>
       *
       * <code>optional string memberid = 3;</code>
       */
      public Builder setMemberidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memberid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phonenumber_ = "";
      /**
       * <pre>
       *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public boolean hasPhonenumber() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public java.lang.String getPhonenumber() {
        java.lang.Object ref = phonenumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phonenumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhonenumberBytes() {
        java.lang.Object ref = phonenumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phonenumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public Builder setPhonenumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        phonenumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public Builder clearPhonenumber() {
        bitField0_ = (bitField0_ & ~0x00000008);
        phonenumber_ = getDefaultInstance().getPhonenumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *电话号码，当为空的时候可以提醒或者在支付之前提示绑定
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public Builder setPhonenumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        phonenumber_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:users_proto.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:users_proto.UserInfo)
    private static final com.network.bbcb.net.proto.UsersProto.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.network.bbcb.net.proto.UsersProto.UserInfo();
    }

    public static com.network.bbcb.net.proto.UsersProto.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      @java.lang.Override
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.network.bbcb.net.proto.UsersProto.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WXLoginRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:users_proto.WXLoginRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *应答结果码
     * </pre>
     *
     * <code>optional uint32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *应答结果码
     * </pre>
     *
     * <code>optional uint32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     *应答结果提示信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <pre>
     *应答结果提示信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <pre>
     *应答结果提示信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional .users_proto.UserInfo data = 3;</code>
     */
    boolean hasData();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional .users_proto.UserInfo data = 3;</code>
     */
    com.network.bbcb.net.proto.UsersProto.UserInfo getData();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional .users_proto.UserInfo data = 3;</code>
     */
    com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code users_proto.WXLoginRsp}
   */
  public  static final class WXLoginRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:users_proto.WXLoginRsp)
      WXLoginRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WXLoginRsp.newBuilder() to construct.
    private WXLoginRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WXLoginRsp() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WXLoginRsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WXLoginRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msg_ = bs;
              break;
            }
            case 26: {
              com.network.bbcb.net.proto.UsersProto.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.network.bbcb.net.proto.UsersProto.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.network.bbcb.net.proto.UsersProto.WXLoginRsp.class, com.network.bbcb.net.proto.UsersProto.WXLoginRsp.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *应答结果码
     * </pre>
     *
     * <code>optional uint32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *应答结果码
     * </pre>
     *
     * <code>optional uint32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <pre>
     *应答结果提示信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *应答结果提示信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *应答结果提示信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.network.bbcb.net.proto.UsersProto.UserInfo data_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional .users_proto.UserInfo data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional .users_proto.UserInfo data = 3;</code>
     */
    public com.network.bbcb.net.proto.UsersProto.UserInfo getData() {
      return data_ == null ? com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional .users_proto.UserInfo data = 3;</code>
     */
    public com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder getDataOrBuilder() {
      return data_ == null ? com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance() : data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.network.bbcb.net.proto.UsersProto.WXLoginRsp)) {
        return super.equals(obj);
      }
      com.network.bbcb.net.proto.UsersProto.WXLoginRsp other = (com.network.bbcb.net.proto.UsersProto.WXLoginRsp) obj;

      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (getCode()
            != other.getCode()) return false;
      }
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.network.bbcb.net.proto.UsersProto.WXLoginRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code users_proto.WXLoginRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:users_proto.WXLoginRsp)
        com.network.bbcb.net.proto.UsersProto.WXLoginRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.network.bbcb.net.proto.UsersProto.WXLoginRsp.class, com.network.bbcb.net.proto.UsersProto.WXLoginRsp.Builder.class);
      }

      // Construct using com.network.bbcb.net.proto.UsersProto.WXLoginRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.network.bbcb.net.proto.UsersProto.internal_static_users_proto_WXLoginRsp_descriptor;
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.WXLoginRsp getDefaultInstanceForType() {
        return com.network.bbcb.net.proto.UsersProto.WXLoginRsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.WXLoginRsp build() {
        com.network.bbcb.net.proto.UsersProto.WXLoginRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.network.bbcb.net.proto.UsersProto.WXLoginRsp buildPartial() {
        com.network.bbcb.net.proto.UsersProto.WXLoginRsp result = new com.network.bbcb.net.proto.UsersProto.WXLoginRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (dataBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = dataBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.network.bbcb.net.proto.UsersProto.WXLoginRsp) {
          return mergeFrom((com.network.bbcb.net.proto.UsersProto.WXLoginRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.network.bbcb.net.proto.UsersProto.WXLoginRsp other) {
        if (other == com.network.bbcb.net.proto.UsersProto.WXLoginRsp.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.network.bbcb.net.proto.UsersProto.WXLoginRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.network.bbcb.net.proto.UsersProto.WXLoginRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       *应答结果码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *应答结果码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *应答结果码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *应答结果码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <pre>
       *应答结果提示信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *应答结果提示信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *应答结果提示信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *应答结果提示信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *应答结果提示信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *应答结果提示信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      private com.network.bbcb.net.proto.UsersProto.UserInfo data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.network.bbcb.net.proto.UsersProto.UserInfo, com.network.bbcb.net.proto.UsersProto.UserInfo.Builder, com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder> dataBuilder_;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public com.network.bbcb.net.proto.UsersProto.UserInfo getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public Builder setData(com.network.bbcb.net.proto.UsersProto.UserInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public Builder setData(
          com.network.bbcb.net.proto.UsersProto.UserInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public Builder mergeData(com.network.bbcb.net.proto.UsersProto.UserInfo value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              data_ != null &&
              data_ != com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance()) {
            data_ =
              com.network.bbcb.net.proto.UsersProto.UserInfo.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public com.network.bbcb.net.proto.UsersProto.UserInfo.Builder getDataBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      public com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.network.bbcb.net.proto.UsersProto.UserInfo.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional .users_proto.UserInfo data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.network.bbcb.net.proto.UsersProto.UserInfo, com.network.bbcb.net.proto.UsersProto.UserInfo.Builder, com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.network.bbcb.net.proto.UsersProto.UserInfo, com.network.bbcb.net.proto.UsersProto.UserInfo.Builder, com.network.bbcb.net.proto.UsersProto.UserInfoOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:users_proto.WXLoginRsp)
    }

    // @@protoc_insertion_point(class_scope:users_proto.WXLoginRsp)
    private static final com.network.bbcb.net.proto.UsersProto.WXLoginRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.network.bbcb.net.proto.UsersProto.WXLoginRsp();
    }

    public static com.network.bbcb.net.proto.UsersProto.WXLoginRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WXLoginRsp>
        PARSER = new com.google.protobuf.AbstractParser<WXLoginRsp>() {
      @java.lang.Override
      public WXLoginRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WXLoginRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WXLoginRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WXLoginRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.network.bbcb.net.proto.UsersProto.WXLoginRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_proto_WXLoginReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_users_proto_WXLoginReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_proto_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_users_proto_UserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_proto_WXLoginRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_users_proto_WXLoginRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013users.proto\022\013users_proto\"\032\n\nWXLoginReq" +
      "\022\014\n\004code\030\001 \001(\t\"N\n\010UserInfo\022\r\n\005token\030\001 \001(" +
      "\t\022\014\n\004uuid\030\002 \001(\t\022\020\n\010memberid\030\003 \001(\t\022\023\n\013pho" +
      "nenumber\030\004 \001(\t\"L\n\nWXLoginRsp\022\014\n\004code\030\001 \001" +
      "(\r\022\013\n\003msg\030\002 \001(\t\022#\n\004data\030\003 \001(\0132\025.users_pr" +
      "oto.UserInfoB(\n\032com.network.bbcb.net.pro" +
      "toB\nUsersProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_users_proto_WXLoginReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_users_proto_WXLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_users_proto_WXLoginReq_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_users_proto_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_users_proto_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_users_proto_UserInfo_descriptor,
        new java.lang.String[] { "Token", "Uuid", "Memberid", "Phonenumber", });
    internal_static_users_proto_WXLoginRsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_users_proto_WXLoginRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_users_proto_WXLoginRsp_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
